project:
  type: website

execute:
  freeze: auto

website:
  title: "Hypothesis Space"
  navbar:
    title: false
    logo: "hslogo.png"
    
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mmhamdy
      - icon: twitter
        href: https://twitter.com/mhamdy_res
        
  comments:
    giscus:
      repo: mmhamdy/Hypothesis-Space
      loading: lazy
       
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css




